#Break Guard config
#Sat Jul 18 16:01:51 BRT 2026
allowSneakOverride=true
enabled=true
minimumDurability=1
playWarningSound=true
protectAllDurabilityItems=true
showWarningMessage=true
warningsBeforeBreak=5
